# ---------------------------------------- #
# ---     makefile for TALYS           --- #
# ---------------------------------------- #

EXEC=talys
INPUT=Ra226_gn.inp
OUTPUT=output

$(OUTPUT): $(INPUT)
	$(EXEC) < $(INPUT) > $(OUTPUT)

all: $(OUTPUT)
